// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type AppUser struct {
	ID           int32
	CreatedAt    sql.NullTime
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
}

type AuthPermission struct {
	ID   int32
	Code string
}

type AuthUsersPermission struct {
	UserID       int64
	PermissionID int64
}

type ContentArticle struct {
	ID          int32
	Title       string
	Slug        string
	Content     string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	PublishedAt sql.NullTime
	DeletedAt   sql.NullTime
	IsPublished sql.NullBool
	IsDeleted   sql.NullBool
}
