.PHONY: train-iris predict-iris train-mnist predict-mnist

train-iris:
	@uv run train_iris.py

predict-iris:
	@uv run predict_iris.py

train-mnist:
	@uv run train_mnist.py

predict-mnist:
	@uv run predict_mnist.py
